[env]
TERM = "xterm-256color"
PATH = "/Users/xmedavid/.nvm/versions/node/v20.15.1/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Library/Apple/usr/bin:/Applications/VMware Fusion.app/Contents/Public:/usr/local/go/bin:/Users/xmedavid/.cargo/bin"
[window]
padding.x = 10
padding.y = 10

#decorations = "Buttonless"

opacity = 0.8

blur = true

option_as_alt = "Both"

[font]
normal.family = "MesloLGS Nerd Font Mono"

size = 18

[terminal]
shell = { program = "/bin/zsh" }

[keyboard]
[[keyboard.bindings]]
key = "Q"
mods = "Alt"
chars = "@"

[[keyboard.bindings]]
key = "2"
mods = "Shift"
chars = "\""

[[keyboard.bindings]]
key = "C"
mods = "Alt"
chars = "รง"

[[keyboard.bindings]]
key = "8"
mods = "Alt"
chars = "["

[[keyboard.bindings]]
key = "9"
mods = "Alt"
chars = "]"

[[keyboard.bindings]]
key = "8"
mods = "Alt|Shift"
chars = "{"

[[keyboard.bindings]]
key = "9"
mods = "Alt|Shift"
chars = "}"
